name: MedAI_Flow_DevSecOps CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  ACR_NAME: medaiflowacr
  AKS_CLUSTER: medai-aks-cluster
  RESOURCE_GROUP: rg-medai-flow
  IMAGE_NAME: medai_flow_backend
  PYTHON_VERSION: '3.11'

jobs:
  # -----------------------
  # 1️⃣ Lint and Security Scan
  # -----------------------
  lint_security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt bandit

      - name: Run lint check (flake8)
        run: |
          pip install flake8
          flake8 backend --count --select=E9,F63,F7,F82 --show-source --statistics || true

      - name: Run security scan (Bandit)
        run: |
          bandit -r backend -ll -ii || true

  # -----------------------
  # 2️⃣ Run Unit Tests
  # -----------------------
  test:
    runs-on: ubuntu-latest
    needs: lint_security
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt pytest

      - name: Run tests
        run: |
          pytest tests/ --maxfail=1 --disable-warnings -q

  # -----------------------
  # 3️⃣ Build and Push Docker Image
  # -----------------------
  build_push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Container Registry login
        run: |
          az acr login --name ${{ env.ACR_NAME }}

      - name: Build and push image
        run: |
          IMAGE_TAG=${{ github.run_number }}
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:$IMAGE_TAG -f backend/Dockerfile .
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:$IMAGE_TAG
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled

  # -----------------------
  # 4️⃣ Deploy to AKS
  # -----------------------
  deploy:
    runs-on: ubuntu-latest
    needs: build_push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER }} --overwrite-existing

      - name: Set IMAGE_TAG
        id: image
        run: echo "TAG=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/medai-backend medai-backend=${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.TAG }} --record
          kubectl rollout status deployment/medai-backend
